# Generated by Django 4.1.5 on 2023-01-06 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название категории', max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_id', models.TextField(help_text='Телеграмм id фото товара')),
                ('name', models.CharField(help_text='Название товара', max_length=160)),
                ('description', models.TextField(help_text='Описание товара')),
                ('price', models.IntegerField(help_text='Цена товара')),
                ('category', models.CharField(max_length=160, verbose_name='Категория товара')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(help_text='Телеграмм id пользователя')),
                ('inviter_id', models.IntegerField(help_text='Телеграмм id приглашателя(реферала)')),
            ],
        ),
    ]
