# Generated by Django 4.1.5 on 2023-01-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inviter_id',
            field=models.IntegerField(default=0, help_text='Телеграмм id приглашателя(реферала)'),
        ),
    ]
