# Generated by Django 4.1.5 on 2023-01-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_user_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.IntegerField(default=0, help_text='Баланс пользователя'),
        ),
    ]
